module.exports = {
    SERVER_REQUEST_ERR: `Prázdna požiadavka`,
    SERVER_PAGE_NOT_FOUND: `Je nám ľúto, ale požadovaná stránka nebola nájdená`,
    SERVER_VALIDATION_ERR: `Údaje boli nesprávne vyplnené`,
    DATABASE_CONNECTED: `Mongo databáza pripojená, adresa:`,
    DATABASE_DISCONNECTED: `Mongo databáza odpojená adresa:`,
    DATABASE_CONNECTION_ERROR: `Pripojenie zlyhalo host: `,
    DATABASE_SEED: `Databáza bola úspešne naplnená údajmi`,
    DATABASE_SEED_ERR: `Databázu sa nepodarilo naplniť údajmi`,
    EUREKA_ERR: `Eureka service registrácia bola úspešná`,
    AUTH_REQUIRED: `Ľutujeme, ale stránka nie je k dispozícií`,
    AUTH_ERR: `Prístup odmietnutý`,

    CREATE_WAREHOUSE_ERR: `Vytvorenie skladu sa nepodarilo, skúste znova`,
    UPDATE_WAREHOUSE_ERR: `Aktualizácia skladu sa nepodarilo, skúste znova`,
    DELETE_WAREHOUSE_ERR: `Odstránenie skladu sa nepodarilo, skúste znova`,
    GET_WAREHOUSE_ERR: `Ľutujeme ale sklad s identifikačním číslom neexistuje`,
    WAREHOUSE_NOT_FOUND: `Ľutujeme ale nenašiel sa žiadný sklad`,

    WAREHOUSE_REGIONS_INT: `Nesprávný formát identifikačného čísla kraja`,
    WAREHOUSE_NAME_LENGHT: `Minimálna dlžka názvu skladu je 3 a maximalná je 64`,
    WAREHOUSE_NAME_ASCII: `Nesprávný formát názov skladu`,
    WAREHOUSE_COUNTRY_LENGHT: `Minimálna dlžka názvu štátu je 3 a maximalná je 64`,
    WAREHOUSE_COUNTRY_ALPHA: `Nesprávný formát názov štátu`,
    WAREHOUSE_ADDRESS_LENGHT: `Minimálna dlžka adresi je 3 a maximalná je 64`,
    WAREHOUSE_ADDRESS_MATCHES: `Nesprávný formát adresi`,
    WAREHOUSE_MONGO_ID: `Nesprávný formát identifikacného čísla`,
    WAREHOUSE_PAGE_NUMBER_INT: `Nesprávný formát číslo strany`,
    WAREHOUSE_PAGE_SIZE_INT: `Nesprávný formát veľkosť strany`,
    WAREHOUSE_COLUMN_NAME_MATCHES: `Nesprávný formát názov stľpca`,
    WAREHOUSE_UNIQUE: `Sklad s údajmi sa už nachádza v databáze`
};